from .connect_wallet import ConnectWalletPharos
from .connect_twitter import ConnectTwitterPharos
from .connect_discord import ConnectDiscordPharos
from .full_registration import FullRegistrationPharos